# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'pulse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pulse
  pod 'Alamofire'
  pod 'Nuke', '~> 7.5.2'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
end
